version: "3.8"

services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    ports:
      # DNS ports (traditional DNS queries)
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - network-internal
      - reverseproxy-nw
    volumes:
      - ${CONFIG_FOLDER}/adguard/work:/opt/adguardhome/work
      - ${CONFIG_FOLDER}/adguard/conf:/opt/adguardhome/conf
    environment:
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguard.sleao.dev`)"
      - "traefik.http.routers.adguard.entrypoints=websecure"
      - "traefik.http.routers.adguard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.adguard.middlewares=authelia@file"
      - "traefik.http.services.adguard.loadbalancer.server.port=3000"

networks:
  network-internal:
  reverseproxy-nw:
    external: true
