version: "3.8"

services:
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    restart: unless-stopped
    ports:
      - 5672:5672
    networks:
      - messaging-internal
      - reverseproxy-nw
    environment:
      RABBITMQ_DEFAULT_USER: ${DB_USER}
      RABBITMQ_DEFAULT_PASS: ${DB_PASS}
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.rabbitmq-http.rule=Host(`rabbitmq.sleao.dev`)"
      - "traefik.http.routers.rabbitmq-http.entrypoints=web"
      # HTTPS router
      - "traefik.http.routers.rabbitmq-https.rule=Host(`rabbitmq.sleao.dev`)"
      - "traefik.http.routers.rabbitmq-https.entrypoints=websecure"
      - "traefik.http.routers.rabbitmq-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.rabbitmq-https.middlewares=authelia@file"
      # Service
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=${DB_PASS}
      - REDIS_TLS_ENABLED=false
      - REDIS_MAXMEMORY=256mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
      - REDIS_APPENDONLY=yes
      - REDIS_APPENDFSYNC=everysec
    networks:
      - messaging-internal
      - reverseproxy-nw

  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${DB_PASS}
    networks:
      - messaging-internal
      - monitoring_monitoring-internal

networks:
  messaging-internal:
  reverseproxy-nw:
    external: true
  monitoring_monitoring-internal:
    external: true
