global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'homelab'
scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'traefik'
    static_configs:
      - targets: ['reverseproxy_traefik:8080']
  - job_name: 'rabbitmq'
    basic_auth:
      username: 'guest'
      password: 'guest'
    static_configs:
      - targets: ['messaging_rabbitmq:15692']
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']
  - job_name: 'mongodb_exporter'
    static_configs:
      - targets: ['mongodb_exporter:9216']
